#!/bin/bash
for container_id in $(docker ps -q); do
    container_name=`docker ps -a | grep $container_id | awk '{print $NF}'`
    iflink=`docker exec -it $container_id bash -c 'cat /sys/class/net/eth0/iflink'`
    iflink=`echo $iflink|tr -d '\r'` veth=`grep -l $iflink /sys/class/net/veth*/ifindex`
    veth=`echo $veth|sed -e 's;^.*net/\(.*\)/ifindex$;\1;'`
    echo $container_name\ \($container_id\)\ \-\>\ $veth
done